BATCH_SIZE: 64
BOARD_SIZE: 8
PASS_ACTION: 64
ACTION_SIZE: 65
MAX_DEPTH: 128

train_param:
  LR: 3e-4
  WEIGHT_DECAY: 1e-4
  VALUE_COEF: 1.0
  CLIP_GRAD: 1.0

MCTS:
  N_SIMS: 800
  BATCH_SIZE: 64
  MAX_NODE: 50000
